---
title: "Supplementary Calculations"
authors: 
  - "Kellen Stark"
  - "Matthew Hoctor, PharmD"
institute: "Oregon Health & Science University-Portland State University, School of Public Health"
date: "`r format(Sys.time(), '%d %B, %Y')`"

toc: TRUE
toc-depth: 2
toc-location: left
toc-title: Contents

code-fold: TRUE
code-overflow: wrap
code-link: TRUE

format: 
  pdf: default
  html: default

editor: source
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# library(dplyr)
library(tidyverse)
# library(readxl)
library(readODS)
# library(rbbt)                 # for citation management tools
# library(ggplot2)            # for ggplot2
# library(ggfortify)          # for ggdistribution function
# library(TeachingDemos)      # for hpd() function
# library(HDInterval)         # for hdi() function
# library(rje)                # for expit function
# library(flextable)
library(knitr)
library(kableExtra)
library(data.table)
library(fmsb)                 # for radar chart/spider plot
# library(ggradar)            # another radar chart package
# library(consortr)
# library(DiagrammeR)
```

```{r helper-functions, include = FALSE}

# this code borrowed from datanovia.com
# https://www.datanovia.com/en/blog/beautiful-radar-chart-in-r-using-fmsb-and-ggplot-packages/#ggplot-radar-chart-using-the-ggradar-r-package

create_beautiful_radarchart <- function(data, color = "#00AFBB", 
                                        vlabels = colnames(data), vlcex = 0.7,
                                        caxislabels = NULL, title = NULL, ...){
  radarchart(
    data, axistype = 1,
    # Customize the polygon
    pcol = color, pfcol = scales::alpha(color, 0.5), plwd = 2, plty = 1,
    # Customize the grid
    cglcol = "grey", cglty = 1, cglwd = 0.8,
    # Customize the axis
    axislabcol = "grey", 
    # Variable labels
    vlcex = vlcex, vlabels = vlabels,
    caxislabels = caxislabels, title = title, ...
  )
}
```

# PRECIS-2 Criteria

```{r}
PRECIS <- read_ods(
  "tables.ods",
  sheet = "PRECIS"
)
```

```{r}
PRECIS |>
  kable() |>
  kable_styling(latex_options = "striped")
```

```{r}
PRECIS2 <- read_ods(
  "tables.ods",
  sheet = "PRECIS2",
  row_names = TRUE,
  as_tibble = FALSE
)
```

```{r}
op <- par(mar = c(1, 2, 2, 1))
create_beautiful_radarchart(
  PRECIS2, 
  caxislabels = c(1,2,3,4,5),
  title = "PRECIS-2 Radar Chart"
)
par(op)
```

\pagebreak

# Session Info

```{r}
sessionInfo()
```